Updated Modes for the WFIRST/Roman CGI
spacetelescope/webbpsf pull request #383
Opened 2020-09-24 04:13 UTC by kian1393

This pull request changes the wfirst.py file such that the CGI class includes the updated SPC modes for F730 and F825. It now refers to the older modes as deprecated, but the deprecated modes are still functional. In order for the new modes to function, the file structure for webbpsf-data has been changed and the Phase-B data files for the 2 new SPC modes have been added. The webbpsf-data also includes the files for the HLC mode, however, that mode is not yet functional in the webbpsf wfirst code. The updated file structure is shown in the picture below and the full webbpsf-data directory is available on box. 

![image](https://user-images.githubusercontent.com/50641386/94084548-a3ad2800-fdba-11ea-8178-aa8cdb708394.png)

In addition, there are 3 new notebooks:
- Roman_deprecated_tests.ipynb: this file demonstrates the functionality of the now deprecated modes.
- Roman_F730_tests.ipynb: this file demonstrates the functionality of the new mode. 
- Roman_F825_tests.ipynb: this file demonstrates the functionality of the new mode. 

Also, two fits files have been added called proper_spcf730_result.fits and proper_spcf825_result.fits. These contain results of off-axis PSFs produced by PROPER in order to compare the Webbpsf results with those of another model. 

It should be noted that the new modes appear to be incorrect when it comes to the on-axis PSFs, whereas the comparison with the PROPER PSFs for the off-axis case show very high agreement; why this is case is still being looked into. Also, the new modes added do not yet support the implementation of OPD files. 

Lastly, credit should also be given to @Jashcraf and @biancalondra for contributing work to make the updated modes.

2020-10-05 16:06 UTC, mperrin requested changes
Hi @kian1393, 

Thanks very much for this contribution! I've reviewed it and have a few suggestions and requests. 

- First, you commented about the on-axis PSFs disagreeing with the PROPER reference calculations. Do you expect to be able to investigate and resolve that sometime soon (prior to merging this PR), or do you think we should merge this now as 'good enough'? What level of disagreement do you see between the two cases? Let me know what you think the next steps should be for this, please. 
- The test notebooks need some updates. First, they contain hard-coded paths to e.g. `/groups/douglase/webbpsf-data/CGI/optics`, so they won't run for anyone else. This should be done with relative paths into webbpsf-data. Next, the notebooks start with some modifications to the FITS files on disk.  It seems that this should be done once and the updated (correct keywords etc) FITS files saved as the ones in the WebbPSF-data directory on Box. It needs to be possible to just invoke the model and perform PSF calculations without having to modify the files each time. If this is already the case, then the notebook needs to be updated. Lastly, the notebook filenames and text in them should probably state 'Roman CGI' not just Roman. 
- See below for additional comments/questions on a few parts of the code. 

I'd also like to suggest some additional areas which could benefit from updates, but may be out of scope for this PR: 
- We should consider moving some of the cross-checks of the coronagraphic PSFs to automated tests in `webbpsf/tests/test_wfirst.py` or perhaps a new `webbpsf/tests/test_roman_cgi.py`, not just having the tests in the notebooks. Are you familiar yet with writing automated software tests? If not it's a good skill to learn and I can point you in the right direction if interested. 
- We should also consider updating the documentation pages to describe the Roman CGI support, and link people to the notebooks. Would you be willing to help with that part too? See `docs/wfirst.rst` for instance. 

Thanks again - I'm really glad to see this update, and I think it's 90+% of the way there already, just needs these few bits polished which I expect to be pretty straightforward. Happy to discuss more for next steps with you, @douglase, and others.

2020-10-05 16:06 UTC, mperrin commented on webbpsf/wfirst.py
> +"""
Remove please :-)

2020-10-05 16:06 UTC, mperrin commented on webbpsf/wfirst.py
> +        'DISKSPC_F721': ('IMAGER','F721','DISKSPC', 'DISKSPC_F721_ANNULUS', 'LS30D88')} # Depreciated Mode
minor: spelling "deprecated"

2020-10-05 16:06 UTC, mperrin commented on webbpsf/wfirst.py
> +                self.fov_arcsec = 2 * 0.55  # 2015 SDT report, Section 3.4.1.1.1:
The IFS was descoped; shouldn't we delete rather than updating this IFS section here?

2020-10-05 16:06 UTC, mperrin commented on webbpsf/wfirst.py
> +        if value == 'HYBRID':
`elif`?

2020-10-05 16:06 UTC, mperrin commented on webbpsf/wfirst.py
> +                                 comment='Full apodizer array size, incl padding.')
The PUPLSCAL and PUPLDIAM keywords are also written below based on the lyot stop header, so these values will be overwritten. This is an oversight in the existing code, not in your code, but perhaps we should fix it now as part of these improvements. We could use for instance APODSCAL and APODDIAM here.

2020-10-05 18:01 UTC, kian1377 commented on webbpsf/wfirst.py
> +"""
This was some pixel art included by Jaren Ashcraft. It helped with scrolling to the section of code being modified and I forgot to delete it in the final uploaded version.

2020-10-05 18:02 UTC, kian1393 commented on webbpsf/wfirst.py
> +                self.fov_arcsec = 2 * 0.55  # 2015 SDT report, Section 3.4.1.1.1:
I was not aware of the IFS being descoped. I remember @douglase mentioned something about the IFS but said to leave it for now. I will speak to him for more clarification regarding this.

2020-10-05 18:04 UTC, kian1393 commented
Hello,

Thank you for the comments. To begin with, I have not had time to further investigate the disagreement in the on-axis PSFs due to academics, however, I am looking to do so in the next couple of weeks. I can add a section showing the on-axis PROPER PSFs similar to how I show the comparison between the off-axis case until it is solved, so at least the disagreement can be seen. 

I can update the notebook as well in order to have the relative paths instead of the hardcoded paths. Regarding the modifications to the fits files, the files already contain the correct keywords and values because of the testing I have been doing, however, I only included that portion of the code such that users can explicitly see what was being done and what values were being set. 

As far as updating the test_wfirst.py file, I do not have experience writing automated software tests, but I am open to learning this in order to update it in a future PR. I am also open to updating the documentation pages, however I am unfamiliar with this as well so please point me in the right direction for these tasks. 

Regards,
Kian Milani

2020-10-06 03:25 UTC, mperrin commented
Hi Kian, 

Great, thanks. For now I would encourage you to focus on the investigation of the on-axis PSFs (as time permits after classes and other academic commitments, for sure). 

The testing and documentation we can sort out later. For now, in case you're curious I will point you at this page: https://docs.pytest.org/en/stable/talks.html and we can talk more later. The basic idea is simple: write a function that checks some desired fact is true about the output of your code (for instance, that the output from the CGI model is within say 5% of the output from the PROPER reference calculation), and then the pytest framework will automatically run that test after every revision of the code, and verify that the result is true. In effect, it can be the same sort of check you already do in your notebooks, but made automatic. This approach to software development and validation has proven to be an effective way to find and prevent bugs; it ensures not only does your test code in the notebook run once when you first develop it, it has to continually run correctly after any later edits to the software, or else it'll raise an alert to let you know. It's a very useful tool to have in your tool kit, particularly for reproducible and reliable scientific computing.  But we can sort all that out later, after we've got the models in better agreement for on-axis as well as off-axis calculations. Cheers!

2021-05-16 19:57 UTC, closed without merging