WebbPSF: Rename WFIRST -> Roman
spacetelescope/webbpsf pull request #400
Opened 2021-01-25 18:04 UTC by robelgeda

This PR aims to replace ``WFIRST`` with ``Roman`` in the WebbPSF codebase as well as docs.

2021-01-25 18:10 UTC, robelgeda commented
@mperrin We could provide backwards compatibility by adding

``import .roman as wfirst``

In `__init__.py` if you think this is a good idea. It would allow people to use the code they already have without having to rename all their imports, and sometimes api calls.

2021-01-25 18:18 UTC, mperrin commented
> import .roman as wfirst

@robelgeda yes, I do think that's a good idea, yes please. In the long run I don't think we should maintain this name alias forever, but it does ease things in the short run for downstream users. And it's super simple to do.

2021-01-25 18:25 UTC, robelgeda commented
Sounds good to me, I have made the update and it seems to work on my local machine.

2021-01-25 18:33 UTC, mperrin requested changes
Looks good overall and I think this is 99% of the way there. The one requested change I would like is to update also the Jupyter notebook `webbpsf/notebooks/WebbPSF-WFIRST_Tutorial.ipynb` as well, please.

2021-01-25 18:33 UTC, mperrin commented on webbpsf/roman.py
> +Roman Instruments (pre-alpha)
We should delete the comment "(pre-alpha)" here, which is no longer true (and hasn't been for a long while! I hadn't realized this was still stated like that...)

2021-01-25 18:33 UTC, mperrin commented on webbpsf/roman.py
> +        pixelscale = 110e-3  # arcsec/px, Roman-AFTA SDT report final version (p. 91)
super minor, but we can also cite https://roman.ipac.caltech.edu/sims/Param_db.html for this (it's the same value, but more current reference than the old WFIRST-AFTA SDT report.)

2021-01-25 18:33 UTC, mperrin commented on docs/roman.rst
> +   This documentation is complemented by an `IPython Notebook tutorial for Roman PSFs <http://nbviewer.ipython.org/github/spacetelescope/webbpsf/blob/stable/notebooks/WebbPSF-WFIRST_Tutorial.ipynb>`_
What about this Jupyter notebook? Seems to me this should also be updated, or at least checked?

2021-01-26 03:11 UTC, mperrin approved these changes
Looks good, thanks Robel.

2021-01-26 03:11 UTC, merged