Add notebooks for plotting JWST SI WFE, and JWST SI MIMF field points
spacetelescope/webbpsf pull request #652
Opened 2023-03-27 15:35 UTC by mperrin

Adds the notebook which makes the [plots of SI WFE included in the docs](https://webbpsf.readthedocs.io/en/latest/jwst.html#si-wfe). 

Also adds the notebook which made the MIMF field points chart that we used in commissioning (independent from but somewhat related to that first notebook). Not sure this will ever be needed again but I realized it was missing from the git repo, along with the SI WFE plots notebook.

These are both added in the `dev_utils` subdirectory, since these are more specialized / less general purpose, and not too likely to be used by typical webbpsf users.

2023-06-01 19:16 UTC, mperrin commented
Reminder this is still waiting on a review from ~months ago, fyi @obi-wan76

2023-06-05 15:33 UTC, obi-wan76 requested changes
A couple of small comments for each notebook

2023-06-05 15:33 UTC, obi-wan76 commented on dev_utils/Plot SI WFE Field Dependence.ipynb
This notebook runs fine except for the last cell:
`main_opd_plot(nircamswa, verbose=True)` which should be `main_opd_plot_isimcv(nircamswa, verbose=True)`
However, when running it returns an error:

> ValueError: Detector pixel coordinates must be nonnegative integers

I think because `nircamswa._tel_coords() = [1.1194241, −6.7511693]′`

2023-06-05 15:33 UTC, marcio-melendez commented on dev_utils/Plot SI MIMF Field Point Locations Wall Chart.ipynb
`webbpsf.Instrument` should be `webbpsf.instrument`
The file MIMF_FP_Table_From_WAG.xlsx is missing

2023-06-05 21:14 UTC, mperrin commented
I added the missing excel reference data file. 

For the plotting of the OPDs for NIRCam coronagraphy, that has never actually worked. The coronagraphy WFE for NIRCam is handled differently because of the Lyot wedges. I may try to make this plotting also work (it's arguably relevant for some science) but it won't happen right away

2023-06-06 14:20 UTC, obi-wan76 commented on dev_utils/Plot SI MIMF Field Point Locations Wall Chart.ipynb
I see the file, there is still the change from `webbpsf.Instrument `to `webbpsf.instrument`.

2023-06-08 14:39 UTC, mperrin commented
I fixed (enhanced) the plotting to also work for NIRCam coronagraphy. This ended up being a semi-substantial bit of work, requiring modifications throughout several parts of the notebook. Working now for me.

2023-06-12 19:23 UTC, obi-wan76 commented on dev_utils/Plot SI WFE Field Dependence.ipynb
This notebook is running in its entirely for me, attach the last figure in NRC Coron LW
![image](https://github.com/spacetelescope/webbpsf/assets/9635910/a229ab94-8514-4beb-8852-6480fe3ed47a)

2023-06-12 20:08 UTC, mperrin commented on dev_utils/Plot SI WFE Field Dependence.ipynb
Great. FYI, I showed this output to @JarronL and he confirmed it looked good (correct) to him.

2023-06-12 20:08 UTC, mperrin commented on dev_utils/Plot SI WFE Field Dependence.ipynb
btw I think you still have to mark it approved in a new review before either of us can merge it

2023-06-13 15:45 UTC, obi-wan76 commented on dev_utils/Plot SI MIMF Field Point Locations Wall Chart.ipynb
@mperrin there is still the pending comment on this notebook, the wall chart, about changing  the instrument class from upper case to lower case.

2023-06-14 14:04 UTC, obi-wan76 approved these changes
Looks good, comments in both notebooks have been resolved. Great addition.

2023-06-14 14:04 UTC, merged