Additional Pep8speaks updates
spacetelescope/webbpsf pull request #856
Opened 2024-05-21 16:32 UTC by BradleySappington

Found a few missed items from the no-formatting transition

2024-05-21 16:32 UTC, pep8speaks commented
Hello @BradleySappington, Thank you for submitting the Pull Request !



* In the file [`dev_utils/field_dependence/basis.py`](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/dev_utils/field_dependence/basis.py):

> [Line 218:28](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/dev_utils/field_dependence/basis.py#L218): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 218:45](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/dev_utils/field_dependence/basis.py#L218): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 218:47](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/dev_utils/field_dependence/basis.py#L218): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

* In the file [`dev_utils/field_dependence/read_codev_dat_fits.py`](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/dev_utils/field_dependence/read_codev_dat_fits.py):

> [Line 49:13](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/dev_utils/field_dependence/read_codev_dat_fits.py#L49): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 50:13](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/dev_utils/field_dependence/read_codev_dat_fits.py#L50): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 51:13](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/dev_utils/field_dependence/read_codev_dat_fits.py#L51): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 52:13](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/dev_utils/field_dependence/read_codev_dat_fits.py#L52): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 53:13](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/dev_utils/field_dependence/read_codev_dat_fits.py#L53): [E124](https://duckduckgo.com/?q=pep8%20E124) closing bracket does not match visual indentation





* In the file [`docs/exts/numfig.py`](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/docs/exts/numfig.py):

> [Line 5:1](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/docs/exts/numfig.py#L5): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1



* In the file [`webbpsf/detectors.py`](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/detectors.py):

> [Line 64:9](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/detectors.py#L64): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 64:126](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/detectors.py#L64): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (149 > 125 characters)
> [Line 171:126](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/detectors.py#L171): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (128 > 125 characters)
> [Line 287:126](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/detectors.py#L287): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 125 characters)
> [Line 318:5](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/detectors.py#L318): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 341:5](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/detectors.py#L341): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment











* In the file [`webbpsf/optics.py`](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/optics.py):

> [Line 20:1](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/optics.py#L20): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 189:1](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/optics.py#L189): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 445:126](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/optics.py#L445): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (175 > 125 characters)
> [Line 515:126](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/optics.py#L515): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (146 > 125 characters)
> [Line 516:126](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/optics.py#L516): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (141 > 125 characters)
> [Line 1408:52](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/optics.py#L1408): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 1408:70](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/optics.py#L1408): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'









* In the file [`webbpsf/tests/test_nircam.py`](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/tests/test_nircam.py):

> [Line 200:126](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/tests/test_nircam.py#L200): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 125 characters)
> [Line 329:126](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/tests/test_nircam.py#L329): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (142 > 125 characters)











* In the file [`webbpsf/trending.py`](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/trending.py):

> [Line 2021:1](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/trending.py#L2021): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment



* In the file [`webbpsf/webbpsf_core.py`](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/webbpsf_core.py):

> [Line 305:126](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/webbpsf_core.py#L305): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (148 > 125 characters)
> [Line 392:47](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/webbpsf_core.py#L392): [E114](https://duckduckgo.com/?q=pep8%20E114) indentation is not a multiple of four (comment)
> [Line 392:47](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/webbpsf_core.py#L392): [E116](https://duckduckgo.com/?q=pep8%20E116) unexpected indentation (comment)
> [Line 730:126](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/webbpsf_core.py#L730): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (152 > 125 characters)
> [Line 757:1](https://github.com/spacetelescope/webbpsf/blob/d0291697989d9fbef35457c84925a370f6b013cf/webbpsf/webbpsf_core.py#L757): [ [...]

2024-05-21 20:04 UTC, mperrin requested changes
Hi @BradleySappington thanks for these edits.  Most looks fine but I have a couple concerns, particularly about line breaks in strings. 

I think using a backslash to break a string across two lines doesn't work in the way you're intending it to here: the whitespace at the start of the second line isn't trimmed out automatically. I tested several of those edits, and the proposed edits do result in extra unintended whitespace in the output strings, so I think those will need to be revised. There are quite a few instances of this, as marked below (I may not have caught them all). 

This is a small thing but I don't think we want to accidentally introduce formatting errors in output messages in the course of cleaning up formatting errors of the code 😆

2024-05-21 20:04 UTC, mperrin commented on .pep8speaks.yml
> +    diff_only: True  # If True, errors caused by only the patch are shown
👏

2024-05-21 20:04 UTC, mperrin commented on dev_utils/field_dependence/read_codev_dat_fits.py
> +    }
(minor) I'm curious what PEP8 rule is relevant for this? What's the style rule or reasoning for preferring the revised version with the one extra newline?   (to be clear I'm fine with this edit; I'm just asking for my own better understanding of why this is a pep8 change)

2024-05-21 20:04 UTC, mperrin commented on webbpsf/detectors.py
> +    # Cases for which user has asked for the IPC to be applied to a not-present extension, we have nothing to add this to
minor, but please change the text back here. Dropping those two words results in a non-sentence which is not clear.

2024-05-21 20:04 UTC, mperrin commented on webbpsf/mast_wss.py
> +                        Date outside of the available range of WFS data.'
Doesn't breaking the string this way result in a bunch of extra added whitespace? I don't think the whitespace at the start of the second line is stripped.  Test running this and the next edit below in both cases do result in strings containing a bunch of whitespace between the two parts. 

Consider splitting this just with two strings, like the following.  

```
                        'Could not find JWST OPDs both before and after the specified date. '
                        'Date outside of the available range of WFS data.'
```

2024-05-21 20:04 UTC, mperrin commented on webbpsf/opds.py
> +            ] /= 1000  # convert Z tilt to milliradians instead of microradians, that is what the sensitivity tables use
minor: This edit results in a grammatically incorrect run-on sentence. I'm not sure what the point of this edit is?

2024-05-21 20:04 UTC, mperrin commented on webbpsf/webbpsf_core.py
> +        self._modes_list = {'imaging': 'MIRIM_FULL', 'IFU': 'MIRIFU_CHANNEL1A'}
This is another case where I'm curious what the reasoning is for the edit. I get that too-long lines should be avoided, but is there some PEP8 reason why it's frowned upon to occasionally add line breaks for clarity in a list or dict literal?   Is this an auto-reformatting that got overzealous or is there some deeper principle why it's not desirable?  I routinely see code with dict literals that has each key as its own line, because that often makes it clearer and easier to read and understand later.

2024-05-21 20:04 UTC, mperrin commented on webbpsf/webbpsf_core.py
> +                      There do not exist corresponding SIAF apertures, so we ignore setting detector geometry.'
another instance of line continuation needing revision

2024-05-21 20:04 UTC, mperrin commented on webbpsf/webbpsf_core.py
> +                          based on average X+Y SciScale at SIAF aperture {self._aperturename}'
here too

2024-05-21 20:04 UTC, mperrin commented on webbpsf/webbpsf_core.py
> +                  minimum set to avoid phase wrap of segment C3 surface.'
also here

2024-05-21 20:04 UTC, mperrin commented on webbpsf/webbpsf_core.py
> +                     Continuing with old aperture names.'
also here

2024-05-21 20:04 UTC, mperrin commented on webbpsf/webbpsf_core.py
> +                      based on average X+Y SciScale at SIAF aperture {self._aperturename}'
also here

2024-05-21 20:04 UTC, mperrin commented on webbpsf/webbpsf_core.py
> +                          based on average X+Y SciScale at SIAF aperture {self._aperturename}'
also here

2024-05-21 20:04 UTC, mperrin commented on webbpsf/webbpsf_core.py
> +                             Setting image_mask=None'
also here

2024-05-21 20:04 UTC, mperrin commented on webbpsf/opds.py
> +                  https://wsstas.stsci.edu/wsstas/staticPage/showContent/RecentSURs?primary=master.png'
line continuation needs revision

2024-05-21 20:04 UTC, mperrin commented on webbpsf/opds.py
> +                      Clipping to closest available valid location, {clip_dist} away from the requested coordinates.'
line continuation needs revision

2024-05-22 14:53 UTC, BradleySappington reviewed
Thanks again for pointing out the formatting mistake!

2024-05-22 14:53 UTC, BradleySappington commented on dev_utils/field_dependence/read_codev_dat_fits.py
> +    }
This is in the "[indentation](https://peps.python.org/pep-0008/#indentation)" section of the Pep8 standards.  Both `hanging` and `aligned` are fine, however the rest of this document uses `aligned` with its closure indicators, this was the only `hanging` instance that I saw.

2024-05-22 14:53 UTC, BradleySappington commented on webbpsf/detectors.py
> +    # Cases for which user has asked for the IPC to be applied to a not-present extension, we have nothing to add this to
No problem!

2024-05-22 14:53 UTC, BradleySappington commented on webbpsf/mast_wss.py
> +                        Date outside of the available range of WFS data.'
I forgot to go back to verify this, thanks for the catch!

2024-05-22 14:53 UTC, BradleySappington commented on webbpsf/opds.py
> +            ] /= 1000  # convert Z tilt to milliradians instead of microradians, that is what the sensitivity tables use
To keep comment under 125 on one line.  I'll just move to leading line.  Thanks!

2024-05-22 14:53 UTC, BradleySappington commented on webbpsf/webbpsf_core.py
> +        self._modes_list = {'imaging': 'MIRIM_FULL', 'IFU': 'MIRIFU_CHANNEL1A'}
This was an auto-format addition.  For the few larger files in this codeset that had a lot of pep8 issues, I used the auto-formatting and then went through and fixed the items that I deemed too much.  This was short enough that I let it stick, but happy to put back as I personally also prefer line delineations for clarity.

2024-05-22 16:56 UTC, BradleySappington commented
@mperrin - updates complete

2024-05-22 20:19 UTC, mperrin approved these changes
Looks good. Thanks @BradleySappington

2024-05-22 20:57 UTC, merged